[tools]
node = "24"
go = "1.26.0"
golangci-lint = "2.9.0"
helm-docs = "1.14.2"
watchexec = "2.3.2"
pnpm = "10.30.0"
stripe = "1.35.0"
"go:github.com/go-delve/delve/cmd/dlv" = "1.26.0"

[env]
_.source = ['hack/current-commit.sh']
DISTR_ENV = '.env.development.local'
VERSION = 'snapshot'
CGO_ENABLED = "0"

[vars]
ldflags = "-s -w -X github.com/distr-sh/distr/internal/buildconfig.version=$VERSION -X github.com/distr-sh/distr/internal/buildconfig.commit=$COMMIT"

[tasks.frontend-deps]
run = 'pnpm install'
sources = ["package.json", "pnpm-lock.yaml"]

[tasks.go-tidy]
run = 'go mod tidy'

[tasks."build:frontend:dev"]
run = 'pnpm build:dev'
depends = ["frontend-deps"]
sources = ["node_modules/**/*", "frontend/ui/**/*"]

[tasks."build:frontend:community"]
run = 'pnpm build:community'
depends = ["frontend-deps"]

[tasks."build:frontend:enterprise"]
run = 'pnpm build:enterprise'
depends = ["frontend-deps"]

[tasks."build:hub:community"]
run = 'go build -ldflags="{{vars.ldflags}} -X github.com/distr-sh/distr/internal/buildconfig.edition=community" -o dist/distr ./cmd/hub'
depends = ["go-tidy", "build:frontend:community"]

[tasks."build:hub:enterprise"]
run = 'go build -ldflags="{{vars.ldflags}} -X github.com/distr-sh/distr/internal/buildconfig.edition=enterprise" -o dist/distr ./cmd/hub'
depends = ["go-tidy", "build:frontend:enterprise"]

[tasks."build:mcp"]
run = 'go build -ldflags="{{vars.ldflags}}" -o dist/mcp-server ./cmd/mcp'
depends = ["go-tidy"]

[tasks."build:agent:docker"]
run = 'go build -ldflags="{{vars.ldflags}}" -o dist/docker-agent ./cmd/agent/docker'
depends = ["go-tidy"]

[tasks."build:agent:kubernetes"]
run = 'go build -ldflags="{{vars.ldflags}}" -o dist/kubernetes-agent ./cmd/agent/kubernetes'
depends = ["go-tidy"]

[tasks."lint:go"]
depends = ["go-tidy"]
run = 'golangci-lint run'

[tasks."lint:frontend"]
run = 'pnpm lint'

[tasks."lint:migrations"]
run = 'hack/validate-migrations.sh'

[tasks.lint]
run = {tasks=["lint:go", "lint:frontend", "lint:migrations"]}

[tasks."test:go"]
run = 'go test ./...'
depends = ["go-tidy"]
description = 'Run all Go tests'

[tasks.test]
run = {tasks=["test:go"]}

[tasks."format:go"]
run = 'golangci-lint run --fix'

[tasks."format:frontend"]
run = 'pnpm format'

[tasks.format]
run = {tasks=["format:go", "format:frontend"]}

[tasks."run:hub:serve"]
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/hub/ serve'
description = 'Only starts the hub, it will not serve the frontend on that port. Protip: "mise watch run:hub:serve -r"'
depends = ["go-tidy"]
sources = ["api/**/*.go", "cmd/**/*.go", "internal/**/*.go"]


[tasks."run:all:serve"]
alias = "serve"
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/hub/ serve'
description = 'Builds the frontend and starts the hub server incl. serving the frontend. Protip: auto-reload with "mise watch serve -r"'
depends = ["go-tidy", "build:frontend:dev"]
sources = ["api/**/*.go", "cmd/**/*.go", "internal/**/*.go"]

[tasks."run:hub:db-migrate"]
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/hub/ migrate'
description = 'Migrate the database to the latest schema version. Protip: `mise run:hub:db-migrate -- --to xx` to migrate to a specific version'

[tasks."run:hub:db-purge"]
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/hub/ migrate --down'

[tasks."run:agent:docker"]
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/agent/docker/ run'

[tasks."run:agent:kubernetes"]
run = 'go run -ldflags="{{vars.ldflags}}" ./cmd/agent/kubernetes/ run'

[tasks."docker-build:hub"]
run = 'docker build -f Dockerfile.hub --tag ghcr.io/distr-sh/distr:$VERSION .'

[tasks."docker-build:agent:docker"]
run = 'docker build -f Dockerfile.docker-agent --tag ghcr.io/distr-sh/distr/docker-agent:$VERSION --build-arg VERSION=$VERSION --build-arg COMMIT=$COMMIT --network host .'

[tasks."docker-build:agent:kubernetes"]
run = 'docker build -f Dockerfile.kubernetes-agent --tag ghcr.io/distr-sh/distr/kubernetes-agent:$VERSION --build-arg VERSION=$VERSION --build-arg COMMIT=$COMMIT --network host .'
